### ISSUE TITLE
Default controller is not shown.

### ISSUE THREAD

**Issue by zhangming170622** [davidmigloz/youtube-android-player-api-gradle#1]
Hi, I am installing Youtube version13.28.54. I load videos by using video id.On other hand, I have used cueVideos(List<String> var1, int var2, int var3). But previous and next play control is not shown.
Why? In previous version Youtube, no problem. I want to your help.

**Comment by davidmigloz** [comment]
Hi, this is not the official Youtube library repository. It is just the 
[YouTube Android Player API](https://developers.google.com/youtube/android/player/) packaged as Gradle dependency.
